### ISSUE TITLE
Double check tracking user

### ISSUE THREAD

**Issue by sdras** [netlify/explorers#251]
- [x] User page should reflect the courses watched and progress
- [x] Tracking component while watching the mission should be updated
- [x] The progress at the bottom should be updated
