### ISSUE TITLE
user tracking schema + CRUD

### ISSUE THREAD

**Issue by jlengstorf** [netlify/explorers#4]
OAuth is already set up as of #139 

to finish this, we need to:

- [x] define the schema required to track user progress in Sanity (see the `/profile` page and [this dummy data](https://github.com/netlify/explorers/blob/4869538dc1761c2592696ff66cf58a2b7b2ed4cb/src/context/user.js#L65-L114) for guidance)
- [x] define mutations for writing progress data
- [x] add update functions to the user context
- [x] call update functions from components as users trigger different events (e.g. the progress event in #106)
