### ISSUE TITLE
User Issue Achievement Reward Workflow

### ISSUE THREAD

**Issue by bencodezen** [netlify/explorers#466]
## Desired User Flow

1. The user watches the last video in a mission
2. Explorers sends a `video-completed` event to Activity Hub
3. Activity Hub fires an event because we wrote data to Activity Hub
4. A webhook runs to determine whether the user has completed a mission 
5. If yes, the webhook writes an achievent object to the Activity Hub database
6. When Activity Hub gets new achievement data written, it fires another webhook
7. The next webhook checks to see if the achievement unlocks a reward
8. If yes, the webhook writes reward data to the rewards database
9. Now Explorers can query the `/achievements` endpoint to get a list of achievements and rewards from Activity Hub
10. On querying, a third function fires to determine whether a given reward has been claimed

Scheme and flow: https://miro.com/app/board/o9J_lWmoARA=/

** Work to enable the above **

- [x] (#475) Before we can start, we have some hasura admin tasks

What happens every time:
- [x] (#471 )Record in the Activity Hub that the `completed-a-mission` achievement has been attained by a user once every stage of any mission has been viewed
- [ ] (#472) Triggered by an update to the `achievements` table in the Activity Hub, check to see if any of the list of achievements earns a reward and if so, update the `rewards` table and `achievements` table to indicate this.
- [ ] (#474) Expose an achievements API which returns all a user's achievements, rewards and claimed status of their rewards
- [ ] (#470) From the front-end, check the achievements API on all logged in navigation events, and update UI if new achievement is present
