### ISSUE TITLE
Add data support for multiple instructors

### ISSUE THREAD

**Issue by tzmanics** [netlify/explorers#515]
## Todo

- [x]  Inspect Sanity schema to change Instructor
- [x]  pull data from `mission.instructors`
- [ ]  Update mission card on /missions
- [x]  Update /learn/:mission
- [x]  Update /learn/:mission/:stage page with authors
